### ISSUE TITLE
本地作业的时候遇到一些问题

### ISSUE THREAD

**Issue by Etherrrr** [ShinyGroup/SCSPTranslationData#1]
由于DumpData分支的文本不是最新就自己dump了一份`local2.json`，不过翻译过程中发现一些奇怪的情况。

图中被框起来的部分已经添加了翻译文本，并且进行了热重载。
但仅有蓝色框的部分被加载了，红色框的部分没有被识别且依旧被dump到了新的`local2.json`中。
![image](https://github.com/ShinyGroup/SCSPTranslationData/assets/20717049/18683ff6-04dd-4b6a-b398-5126d67a87d5)
![image](https://github.com/ShinyGroup/SCSPTranslationData/assets/20717049/698f6fed-5943-4465-a9c5-3e557c9b2891)

尝试替换了下`localify.json`中的同内容文本，进行热重载后可以正常显示中文。
![image](https://github.com/ShinyGroup/SCSPTranslationData/assets/20717049/c0d89579-26ce-4440-91d2-5b4efcc2f11e)

保留`local2.json`中已翻译的部分重新dump，已经翻译的部分会被当做未翻译，被dump到新的`local2.json`中。

删除`local2.json`中的已翻译部分，热重载后显示依旧正常。
重新dump`local2.json`，已经翻译的部分依旧会被dump到新的`local2.json`中。
![image](https://github.com/ShinyGroup/SCSPTranslationData/assets/20717049/e4747b24-a9ae-4a7e-93ef-dfab7c159052)

总结下是
i)对`local2.json`进行翻译->只有一小部分能显示
ii)翻译`localify.json`中i)无法显示的部分->正常显示
iii)无论`local2.json`中是否保留i)无法显示的部分，该部分文本都会被dump到新的`local2.json`。

推测可能是local2.json的dump方式导致的🤔？

**Comment by chinosk6** [comment]
`local2.json` 中文本的应用逻辑是，检查 `UITextMeshProUGUI.get_LocalizeOnAwake -> bool` 这个函数的返回值确定的，若返回 `false` 才应用。实际情况下，很多时候游戏进行了 `Localize` 处理，但这个函数仍然返回 `false`，这种情况下，就会出现上述问题（万南真的是😡）。
我试着优化一下插件文本的加载逻辑吧

**Comment by chinosk6** [comment]
本体仓库最新的提交中优化了 `localify.json` 的加载逻辑。若 `local2.json` 中有相同的键值，会将 `local2.json` 中的翻译应用到 `localify.json` 中。
不过还是建议优先翻译 `localify.json`。遇到无法覆盖的部分，再使用 `local2.json` 翻译~

**Comment by Etherrrr** [comment]
感谢优化！
不过我这边编译环境有些问题所以可能需要一个新的release🤕

**Comment by chinosk6** [comment]
> 感谢优化！ 不过我这边编译环境有些问题所以可能需要一个新的release🤕

有 [Actions](https://github.com/chinosk6/scsp-localify/actions/runs/7735183655)，可以直接下载
